課題3-1
Genki8723/Practice_JS6 pull request #1
Opened 2020-09-23 03:43 UTC by Genki8723

2020-09-23 12:49 UTC, myzktkyk requested changes
動作は問題ありませんでした。
…なのですが、今の実装方法ですとタスク状態変更機能など
今後様々な機能を追加する際に苦労することになります。
今のうちに以下のような実装方法に変更しましょう！

1. 入力されたタスク内容とその状態（デフォルトでは作業中）をオブジェクトで管理する
2. 上記のオブジェクトをはtodosという名前の配列に追加することで、複数のタスクを管理する。
3. todo配列の内容を表示させる関数（displayTodos）を定義する

オブジェクトの内容は以下のような感じになります。

```
todo = {
            task: '入力されたタスク'
            status: '作業中'
       }
```

タスクが入力される度に、この todo オブジェクトを todos という配列に push し
todos 配列にタスクをためていく感じです！

2020-09-23 12:49 UTC, myzktkyk commented on index.html
> +    removeButton.addEventListener('click', () => removeTask(removeButton));
`removeTask` という関数が見当たりません…どこにあるのでしょうか？

2020-10-19 15:51 UTC, manaberuit reviewed
よく記述できいますね！
一点だけ気になる点があったのでコメントしました^^

2020-10-19 15:51 UTC, manaberuit commented on main.js
> +const showTodoList = () => {
こちらの関数が実行される処理がないようですが、いかがでしょうか？

2020-10-21 13:51 UTC, manaberuit approved these changes
OKです！

2020-10-23 14:49 UTC, manaberuit reviewed
一点だけコメントしました^^

2020-10-23 14:49 UTC, manaberuit commented on main.js
> +      })
せっかくですので、こちらの削除ボタンを生成する処理を
createDelBtn
という関数で処理するようにしてみましょう！

2020-10-25 15:05 UTC, yusuke-tnb reviewed
２点コメントしましたので、ご確認ください。

2020-10-25 15:05 UTC, yusuke-tnb commented on main.js
> +      }
関数の定義は一連の処理の流れの外に記述する必要があります。
ですので、10行目あたりに持ってきた方が良いですね。

ただ、そうするとindexの値が読み込めなくなると思いますので、
indexは引数から取得するようにしましょう。

2020-10-25 15:05 UTC, yusuke-tnb commented on main.js
> +      const createDelBtn = () => {
また、作成したcreatDelBtnという関数を実行していないかと思います。
実行する処理をこちらに記述する必要がありますね。

また、実行したときに関数内で生成したdelButtonを受け取る必要があるので、
returnさせる必要があります。

2020-10-27 04:25 UTC, manaberuit reviewed
あれ？
こちらって動作していますか？
createDelBtnで受け取るのはdelButtonではなく、indexとなります。
また、51行目でreturnしたdelButtonを引数に格納しないといけないですよ。

2020-11-01 01:10 UTC, niganium reviewed
お疲れ様です。
何点かコメントをいたしました。修正したのち再提出をお願いいたします。

2020-11-01 01:10 UTC, niganium commented on main.js
> +    todo.state = todoBtn;
stateの中身がbuttonになっています。
こちら作業中や完了などの文字列を入れるべきだと思います。
また、ボタンを生成あとのtextContentは、state内部の文字列を参照した方が取り回しがしやすいかと個人的に思いました。

2020-11-01 01:10 UTC, niganium commented on main.js
> +    todo.state = todoBtn;
またクリック後の処理がここで止まっているため、配列が空のままなうえ、画面上でもなにも動作がしていない状態となります。
その後の処理を記載し、要件通りの処理が実行されているか確認しましょう。

2020-11-01 01:10 UTC, niganium commented on main.js
> +      idNumber.textContent = index + 1;
配列のインデックスは０から始まるので、+1せずとも最初から要件通りの値になると思います。(違っていたらすいません)

2020-11-01 01:10 UTC, niganium commented on main.js
> +    todo.value = todoTable;
やはりvalueですと入力物と混同するためcontentやtaskなどの名称にした方が良いです

2020-11-03 17:45 UTC, merged