表示変更
Genki8723/Practice_JS6 pull request #3
Opened 2020-11-10 12:45 UTC by Genki8723

2020-11-19 01:09 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください！

2020-11-19 01:09 UTC, kouki-iwahara commented on index.html
> +    <tr>
theadの方が設計としてあっていますが、trに変更したのは何か理由がありますか？

2020-11-19 01:09 UTC, kouki-iwahara commented on index.html
> +  <input id="inputTask" type="text" value="">
html側では、単語はキャメルケースではなくハイフンで繋ぎましょう。

2020-11-19 01:09 UTC, kouki-iwahara commented on main.js
>  'use strict';
即時関数を削除した理由は何ですか？

2020-11-19 01:09 UTC, kouki-iwahara commented on main.js
> +      let workingTodos;
todoの状態ごとに配列を作成したようですが、todosの配列を状態によりfilterし、返却された値をそのまま使用できれば、グローバルで宣言する必要がなくなります。

2020-11-19 01:09 UTC, kouki-iwahara commented on main.js
> +          workingTodos = todos.filter(todo => todo.state === '作業中');
先にコメントした箇所と同じなのですが、この変数をグローバルで保持する必要はないので、
`const workingTodos = todos.filter(todo => todo.state === '作業中');`
のようにしてスコープを狭めると良いですね。

2020-11-19 01:09 UTC, kouki-iwahara commented on main.js
> +        taskName.value = "";
文字列は`''`で統一すると良いです。

2020-11-20 09:17 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください！

2020-11-20 09:17 UTC, kouki-iwahara commented on main.js
> +    for (let i = 0; i < arrayTodo.length; i++)
配列に対してfor文はほぼ使用されません。
配列のループ処理は便利なものが色々ありますので、配列のループ処理はそれらが使用できないかをまず検討しましょう。
今回はforEachで良いかと思います。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2020-11-20 09:17 UTC, kouki-iwahara commented on main.js
> +      delBtn.innerHTML = "削除";
修正漏れかと思いますが、文字列は`''`で囲みましょう。

2020-11-23 12:24 UTC, myzktkyk requested changes
実行時にエラーが出ているようで、課題が提示している仕様を満たせていません。
再度確認をお願いします 🙏

2020-11-23 12:24 UTC, myzktkyk commented on main.js
> +      if (workingTodos[id].state === '作業中')
`workingTodos` と言う変数がどこにも定義されていないようです。

2020-12-28 02:30 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください！

2020-12-28 02:30 UTC, kouki-iwahara commented on main.js
> +        let id = this.getAttribute('id');
constで定義できるようです。
125行目も同様です。

2020-12-28 02:30 UTC, kouki-iwahara commented on main.js
> +          console.log('firstCheck');
不要なログ出力であれば削除しましょう。

2021-01-07 18:23 UTC, merged